/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestion_formation.ui;

import gestion_formation.model.DAO.ECFDAO;
import gestion_formation.model.ECF;
import gestion_formation.model.Formation;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Valannos
 */
public class ECFForm extends javax.swing.JDialog {
    
    Formation importedForm;
    private ECFListModel ecfModel;
    private ECF currentECF;
    private int ECFId;
    private int indexModel;

    /**
     * Creates new form ECFForm
     *
     * @param parent
     * @param modal
     * @param form : selected formation in JTable
     * @param ecfModel
     */
    public ECFForm(java.awt.Frame parent, boolean modal, Formation form, ECFListModel ecfModel) {
        
        super(parent, modal);
        this.importedForm = form;
        initComponents();
        this.ecfModel = ecfModel;
        this.ECFId = 0;
        
        
    }
    
    public ECFForm(java.awt.Frame parent, boolean modal, Formation form, ECFListModel ecfModel, ECF toEditECF, int index) {
        
        super(parent, modal);
        this.importedForm = form;
        this.ecfModel = ecfModel;
        this.currentECF = toEditECF;
        this.indexModel = index;
        initComponents();
        this.ECFId = toEditECF.getId();
        jTextField_ECF_Name.setText(toEditECF.getNom());
        jTextArea_Desc_ECF.setText(toEditECF.getDescription());
        JLabel_ECF_FormTitle.setText("Edition de l'ECF " + toEditECF.getNom() + ".");
        
    }
    
    private ECFForm(JFrame jFrame, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLabel_ECF_FormTitle = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField_ECF_Name = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_Desc_ECF = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        JLabel_ECF_FormTitle.setText("Ajouter un ECF à la formation : " + this.importedForm +".");

        jLabel2.setText("Nom de l'ECF");

        jLabel3.setText("Descriptif");

        jTextArea_Desc_ECF.setColumns(20);
        jTextArea_Desc_ECF.setRows(5);
        jScrollPane1.setViewportView(jTextArea_Desc_ECF);

        jButton1.setText("Confirmer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Annuler");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLabel_ECF_FormTitle)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_ECF_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButton1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton2))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLabel_ECF_FormTitle)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_ECF_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        if (this.ECFId == 0) {
            
            if (jTextField_ECF_Name.getText().isEmpty() || jTextArea_Desc_ECF.getText().isEmpty()) {
                
                JOptionPane.showMessageDialog(this, "Certains champs ne sont pas remplis", "Erreur", JOptionPane.ERROR_MESSAGE);
                
            } else {
                
                ECF ecf = new ECF(jTextField_ECF_Name.getText(), this.importedForm, jTextArea_Desc_ECF.getText());
                if (ECFDAO.addECFToFormation(ecf)) {
                    
                    JOptionPane.showMessageDialog(this, "L'ECF " + ecf.getNom() + " a bien été rajouté à la formation + " + ecf.getFormation().getNom() + ".", "Confirmation", JOptionPane.INFORMATION_MESSAGE);
                   //ecfModel.removeECF(indexModel);
                    ecfModel.addECF(ecf);
                    this.dispose();
                    
                }
                
            }
            
        } else {
            
            if (jTextField_ECF_Name.getText().isEmpty() || jTextArea_Desc_ECF.getText().isEmpty()) {
                
                JOptionPane.showMessageDialog(this, "Certains champs ne sont pas remplis", "Erreur", JOptionPane.ERROR_MESSAGE);
                
            } else {
                
                ECF ecf = new ECF(this.ECFId, jTextField_ECF_Name.getText(), this.importedForm, jTextArea_Desc_ECF.getText());
                if (ECFDAO.editECf(ecf)) {
                    
                    JOptionPane.showMessageDialog(this, "L'ECF " + ecf.getNom() + " a bien été mis à jour + " + ecf.getFormation().getNom() + ".", "Confirmation", JOptionPane.INFORMATION_MESSAGE);
                    ecfModel.addECF(ecf);
                    this.dispose();
                    
                }
                
            }
            
        }
        

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ECFForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ECFForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ECFForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ECFForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ECFForm dialog = new ECFForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabel_ECF_FormTitle;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea_Desc_ECF;
    private javax.swing.JTextField jTextField_ECF_Name;
    // End of variables declaration//GEN-END:variables
}
