/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestion_formation.ui;

import gestion_formation.model.DAO.FormationDAO;
import gestion_formation.model.Formation;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author vanel
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        this.setTitle("Gestionnaire de formations");
        this.setSize(500, 500);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
 
        
        
        
  

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Tabs = new javax.swing.JTabbedPane();
        JPanel_Tab_Formations = new javax.swing.JPanel();
        JScrollPane_Formations = new javax.swing.JScrollPane();
        JTable_Formations = new javax.swing.JTable();
        jPanel_Btns_Formations = new javax.swing.JPanel();
        JButton_Edit_Formation = new javax.swing.JButton();
        jButton_Add_Formation = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        JPanel_tab_Stagiaires = new javax.swing.JPanel();
        jScrollPane_Stagiaire = new javax.swing.JScrollPane();
        jTable_Stagiaires = new javax.swing.JTable();
        jTabbedPane_Stagiaires = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem_Add_Formation = new javax.swing.JMenuItem();
        jMenuItem_Add_ECF = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem_Quit = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem_Edit_Formation = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JTable_Formations.setModel(new FormationModel());
        JTable_Formations.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                JTable_FormationsComponentShown(evt);
            }
        });
        JScrollPane_Formations.setViewportView(JTable_Formations);

        JButton_Edit_Formation.setText("Editer Formation");
        JButton_Edit_Formation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_Edit_FormationActionPerformed(evt);
            }
        });

        jButton_Add_Formation.setText("Créer Formation");
        jButton_Add_Formation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Add_FormationActionPerformed(evt);
            }
        });

        jButton1.setText("Ajouter un ECF");

        javax.swing.GroupLayout jPanel_Btns_FormationsLayout = new javax.swing.GroupLayout(jPanel_Btns_Formations);
        jPanel_Btns_Formations.setLayout(jPanel_Btns_FormationsLayout);
        jPanel_Btns_FormationsLayout.setHorizontalGroup(
            jPanel_Btns_FormationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Btns_FormationsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_Add_Formation)
                .addGap(18, 18, 18)
                .addComponent(JButton_Edit_Formation)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_Btns_FormationsLayout.setVerticalGroup(
            jPanel_Btns_FormationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_Btns_FormationsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_Btns_FormationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JButton_Edit_Formation)
                    .addComponent(jButton_Add_Formation)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        javax.swing.GroupLayout JPanel_Tab_FormationsLayout = new javax.swing.GroupLayout(JPanel_Tab_Formations);
        JPanel_Tab_Formations.setLayout(JPanel_Tab_FormationsLayout);
        JPanel_Tab_FormationsLayout.setHorizontalGroup(
            JPanel_Tab_FormationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JScrollPane_Formations, javax.swing.GroupLayout.DEFAULT_SIZE, 739, Short.MAX_VALUE)
            .addComponent(jPanel_Btns_Formations, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JPanel_Tab_FormationsLayout.setVerticalGroup(
            JPanel_Tab_FormationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel_Tab_FormationsLayout.createSequentialGroup()
                .addComponent(JScrollPane_Formations, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_Btns_Formations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Tabs.addTab("Formation", JPanel_Tab_Formations);

        jTable_Stagiaires.setModel(new StagiaireModel());
        jScrollPane_Stagiaire.setViewportView(jTable_Stagiaires);

        javax.swing.GroupLayout JPanel_tab_StagiairesLayout = new javax.swing.GroupLayout(JPanel_tab_Stagiaires);
        JPanel_tab_Stagiaires.setLayout(JPanel_tab_StagiairesLayout);
        JPanel_tab_StagiairesLayout.setHorizontalGroup(
            JPanel_tab_StagiairesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane_Stagiaire, javax.swing.GroupLayout.DEFAULT_SIZE, 739, Short.MAX_VALUE)
            .addComponent(jTabbedPane_Stagiaires)
        );
        JPanel_tab_StagiairesLayout.setVerticalGroup(
            JPanel_tab_StagiairesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel_tab_StagiairesLayout.createSequentialGroup()
                .addComponent(jScrollPane_Stagiaire, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane_Stagiaires, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Tabs.addTab("Stagiaires", JPanel_tab_Stagiaires);

        jMenu1.setText("Fichier");

        jMenuItem_Add_Formation.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem_Add_Formation.setText("Nouvelle formation");
        jMenuItem_Add_Formation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_Add_FormationActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_Add_Formation);

        jMenuItem_Add_ECF.setText("Ajouter un ECF");
        jMenu1.add(jMenuItem_Add_ECF);
        jMenu1.add(jSeparator1);

        jMenuItem_Quit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem_Quit.setText("Quitter");
        jMenuItem_Quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_QuitActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_Quit);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Edition");

        jMenuItem_Edit_Formation.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem_Edit_Formation.setText("Editer Formation");
        jMenuItem_Edit_Formation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_Edit_FormationActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem_Edit_Formation);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("?");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Tabs)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(Tabs)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    private void JButton_Edit_FormationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_Edit_FormationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JButton_Edit_FormationActionPerformed

    private void jMenuItem_QuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_QuitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem_QuitActionPerformed

    private void JTable_FormationsComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_JTable_FormationsComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_JTable_FormationsComponentShown

    private void jButton_Add_FormationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Add_FormationActionPerformed
        showFormationFormJDiag();
    }//GEN-LAST:event_jButton_Add_FormationActionPerformed

    private void jMenuItem_Add_FormationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_Add_FormationActionPerformed
        showFormationFormJDiag();
    }//GEN-LAST:event_jMenuItem_Add_FormationActionPerformed

    private void jMenuItem_Edit_FormationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_Edit_FormationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem_Edit_FormationActionPerformed

    
    private void showFormationFormJDiag() {

        FormationForm formationForm = new FormationForm(this, true);
        formationForm.setVisible(true);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButton_Edit_Formation;
    private javax.swing.JPanel JPanel_Tab_Formations;
    private javax.swing.JPanel JPanel_tab_Stagiaires;
    private javax.swing.JScrollPane JScrollPane_Formations;
    private javax.swing.JTable JTable_Formations;
    private javax.swing.JTabbedPane Tabs;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_Add_Formation;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem_Add_ECF;
    private javax.swing.JMenuItem jMenuItem_Add_Formation;
    private javax.swing.JMenuItem jMenuItem_Edit_Formation;
    private javax.swing.JMenuItem jMenuItem_Quit;
    private javax.swing.JPanel jPanel_Btns_Formations;
    private javax.swing.JScrollPane jScrollPane_Stagiaire;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane_Stagiaires;
    private javax.swing.JTable jTable_Stagiaires;
    // End of variables declaration//GEN-END:variables

}
